---
title:    |
          | Empirical problem set
          | BUS456 Fall 2022
author: |
        | Group 12
        | Ekaterina Poruchikova - s222650
        | Jhih-Jiuan Cheng - s222648
        | Shuta Yamada - s222422
        | Maximilian Sammeer - s222688
date: "`r Sys.Date()`"
output: pdf_document
---

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo = FALSE, message = FALSE}
library(stargazer) # Pretty statistics output
library(purrr) # Iterations
library(dplyr) 
library(scales) # Turn decimals in %
```



```{r, echo = FALSE}
setwd('C:/Users/steef/Documents/NHH/BUS456 Behavioral Business Strategy/BUS456-Assignment-1')

# Read the file
auto <- read.csv('automated_anonymous.csv')
```

# Question 1

Table 1 shows the frequency of the claimcolour: Green claim is 5674, Red is 1492, Yellow is 13190. Table 2 presents the the insurance type, where auto is 7562, life is 2305, other is 35, property is 5865, travel is 4589.

```{r question-1, echo = FALSE}
# Transform to factor variables
claiminternalnumber <- as.data.frame(auto[, 1])
names(claiminternalnumber)[names(claiminternalnumber) == 'auto[, 1]'] <-
  'claiminternalnumber'

auto[, -1] %>%
  map(as.factor) %>%
  cbind(claiminternalnumber, .) -> auto
rm(claiminternalnumber)

knitr::kable(t(table(auto$claimcolour)),
             caption = 'Frequency of the claim colour')
knitr::kable(t(table(auto$insurancetype)),
             caption = 'Frequency of the insurance type')

# Find insurance claims with empty insurance types
empty.insurance.type <-
  which(auto$insurancetype == '', arr.ind = TRUE)
print(paste(
  'Insurance claim with empty insurance type:',
  empty.insurance.type
))

# Remove these observations from the sample
auto <- auto[-c(17857, 18515), ]
```

**Comment on question 1**

# Question 2

```{r question-2, echo = FALSE}
auto$green <- ifelse(auto$claimcolour == 'Green', 1, 0)
auto$yellow <- ifelse(auto$claimcolour == 'Yellow', 1, 0)
auto$red <- ifelse(auto$claimcolour == 'Red', 1, 0)

# EXCLUDE THE OTHER CATEGORY *************************************************************************

auto %>% # How to label as percentages? *******************************************************
  summarise(
    green = mean(green),
    yellow = mean(yellow),
    red = mean(red)
  ) %>%
  knitr::kable(caption = 'Percentage of claim color')

auto %>% 
  group_by(insurancetype) %>%
  summarise(
    green = mean(green),
    yellow = mean(yellow),
    red = mean(red)
  ) %>%
  knitr::kable(caption = 'Percentage of claim color by insurance type')
```

# Question 3


```{r question-3, echo = FALSE}
auto %>%
  group_by(treatmentgroup) %>%
  summarise(
    green = mean(green),
    yellow = mean(yellow),
    red = mean(red),
    auto = mean(insurancetype == 'auto'),
    life = mean(insurancetype == 'life'),
    property = mean(insurancetype == 'property'),
    travel = mean(insurancetype == 'travel'),
    other = mean(insurancetype == 'other'),
    privatefinanced = mean(as.numeric(as.character(privatefinanced)))
  ) %>%
  t(.) %>%
  knitr::kable(caption = 'Title')

```

# Question 4

```{r question-4, echo = FALSE}
# Create 4 dummy variables
auto$simplification <-
  ifelse(as.character(auto$treatmentgroup) == '1', 1, 0)
auto$personalization <-
  ifelse(as.character(auto$treatmentgroup) == '2', 1, 0)
auto$social.norm <-
  ifelse(as.character(auto$treatmentgroup) == '3', 1, 0)
auto$combined <-
  ifelse(as.character(auto$treatmentgroup) == '4', 1, 0)

auto$accept_automatic <-
  as.numeric(as.character(auto$accept_automatic))

linear.model <-
  lm(accept_automatic ~ simplification + personalization +
       social.norm + combined,
     auto)
```

# Question 5

```{r question-5, echo = FALSE, results='asis'}
linear.model.w.controls <-
  lm(accept_automatic ~ simplification + personalization + social.norm + 
       combined + insurancetype + red + green + privatefinanced, auto)
stargazer(linear.model, linear.model.w.controls, header = FALSE)
```

# Question 6

```{r question-6, echo = FALSE, results='asis'}
auto %>%
  filter(treatmentgroup == 0 | treatmentgroup == 4) %>%
  filter(claimcolour == 'Green') %>%
  lm(accept_automatic ~ combined, .) -> model.green

auto %>%
  filter(treatmentgroup == 0 | treatmentgroup == 4) %>%
  filter(claimcolour == 'Yellow') %>%
  lm(accept_automatic ~ combined, .) -> model.yellow

auto %>%
  filter(treatmentgroup == 0 | treatmentgroup == 4) %>%
  filter(claimcolour == 'Red') %>%
  lm(accept_automatic ~ combined, .) -> model.red

stargazer(model.green, model.yellow, model.red, header = FALSE, 
          column.labels = c('Green', 'Yellow', 'Red'))
```

# Question 7

```{r question-7, echo = FALSE, results='asis'}
# Transform to factors 
auto$accept_automatic <- as.factor(auto$accept_automatic)

# Logit regression
logit.model <- glm(accept_automatic ~ claimcolour + treatmentgroup + 
                     insurancetype + privatefinanced, auto, 
                   family = 'binomial')

stargazer(logit.model, header = FALSE)
```
